version: "3.9"

services:
  db:
    image: postgres:16
    container_name: gea_trader_db

    environment:
      POSTGRES_DB: gea_trader
      POSTGRES_USER: luscious
      POSTGRES_PASSWORD: blue

    ports:
      - "5432:5432"

    volumes:
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
