# Generated by Django 5.2.12 on 2026-04-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='users', through='tenancy.TenantMembershipModel', to='tenancy.tenantmodel'),
        ),
    ]
