# Generated by Django 5.2.12 on 2026-04-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermodel_options'),
        ('tenancy', '0003_alter_tenantgroupmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Businesses this account can access through business access records.', related_name='users', through='tenancy.TenantMembershipModel', to='tenancy.tenantmodel', verbose_name='Businesses'),
        ),
    ]
