# Generated by Django 5.2.12 on 2026-04-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_tenantgroupmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantgroupmodel',
            options={'ordering': ('tenant__name', 'group__name', 'id'), 'verbose_name': 'Business group', 'verbose_name_plural': 'Business groups'},
        ),
        migrations.AlterModelOptions(
            name='tenantmembershipmodel',
            options={'ordering': ('tenant__name', 'user__username', 'id'), 'verbose_name': 'Business access', 'verbose_name_plural': 'Business access'},
        ),
        migrations.AlterModelOptions(
            name='tenantmodel',
            options={'ordering': ('name',), 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterField(
            model_name='tenantmembershipmodel',
            name='role',
            field=models.CharField(choices=[('master', 'Master'), ('owner', 'Owner'), ('operator', 'Operator')], default='owner', max_length=16),
        ),
    ]
