# Generated by Django 5.2.12 on 2026-04-03 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenancy', '0003_alter_tenantgroupmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantgroupmodel',
            name='group',
            field=models.OneToOneField(help_text='Django auth group scoped to the selected business.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_binding', to='auth.group', verbose_name='Permission group'),
        ),
        migrations.AlterField(
            model_name='tenantgroupmodel',
            name='tenant',
            field=models.ForeignKey(help_text='Business that owns this permission group.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_groups', to='tenancy.tenantmodel', verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='tenantmembershipmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this to keep the access record without allowing day-to-day access.', verbose_name='Access active'),
        ),
        migrations.AlterField(
            model_name='tenantmembershipmodel',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Marks this as the default business access used as a fallback context for the account.', verbose_name='Primary access'),
        ),
        migrations.AlterField(
            model_name='tenantmembershipmodel',
            name='role',
            field=models.CharField(choices=[('master', 'Master'), ('owner', 'Owner'), ('operator', 'Operator')], default='owner', help_text='Role this account will have inside the selected business.', max_length=16, verbose_name='Business role'),
        ),
        migrations.AlterField(
            model_name='tenantmembershipmodel',
            name='tenant',
            field=models.ForeignKey(help_text='Business where this account receives access.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.tenantmodel', verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='tenantmembershipmodel',
            name='user',
            field=models.ForeignKey(help_text='Account that receives this business access.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tenantmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this to hide the business from active business selection and day-to-day use.', verbose_name='Business active'),
        ),
        migrations.AlterField(
            model_name='tenantmodel',
            name='name',
            field=models.CharField(help_text='Public name used to identify this business across the admin.', max_length=255, verbose_name='Business name'),
        ),
        migrations.AlterField(
            model_name='tenantmodel',
            name='slug',
            field=models.SlugField(help_text='Stable URL-friendly identifier for this business.', max_length=255, unique=True, verbose_name='Business slug'),
        ),
    ]
