# Generated by Django 5.2.12 on 2026-07-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_alter_tenantmodel_business_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembershipmodel',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('operator', 'Operator')], default='owner', help_text='Role this account will have inside the selected business.', max_length=16, verbose_name='Business role'),
        ),
    ]
