# Generated by Django 5.2.12 on 2026-04-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_alter_tenantgroupmodel_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBrandingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Optional public name used instead of the business name when branding is shown.', max_length=255, verbose_name='Display name')),
                ('logo_light', models.ImageField(blank=True, help_text='Logo variant intended for light backgrounds.', upload_to='branding/logos/', verbose_name='Light logo')),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo variant intended for dark backgrounds.', upload_to='branding/logos/', verbose_name='Dark logo')),
                ('icon_light', models.ImageField(blank=True, help_text='Compact icon variant intended for light backgrounds.', upload_to='branding/icons/', verbose_name='Light icon')),
                ('icon_dark', models.ImageField(blank=True, help_text='Compact icon variant intended for dark backgrounds.', upload_to='branding/icons/', verbose_name='Dark icon')),
                ('favicon_light', models.ImageField(blank=True, help_text='Favicon variant intended for light browser themes or light backgrounds.', upload_to='branding/favicons/', verbose_name='Light favicon')),
                ('favicon_dark', models.ImageField(blank=True, help_text='Favicon variant intended for dark browser themes or dark backgrounds.', upload_to='branding/favicons/', verbose_name='Dark favicon')),
                ('login_image', models.ImageField(blank=True, help_text='Large image that can be reused on login or access screens.', upload_to='branding/login/', verbose_name='Login image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(help_text='Business that owns this branding configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenancy.tenantmodel', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Business branding',
                'verbose_name_plural': 'Business branding',
                'ordering': ('tenant__name', 'id'),
            },
        ),
    ]
