# Generated by Django 5.2.12 on 2026-04-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_tenantbrandingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantbrandingmodel',
            name='login_image',
        ),
    ]
