""" Shared tenant-aware behavior for media storage backends. """

from django.core.files.base import File
from core.config.storage.media_storage.paths.tenant_media_path_builder import TenantMediaPathBuilder


class TenantAwareMediaStorageMixin:
    """ Prefix media object names with the active tenant folder at save time. """

    path_builder_class = TenantMediaPathBuilder

    def save(self, name: str | None, content: File, max_length: int | None = None) -> str:
        """ Save a media object under the active tenant folder when available.

        Args:
            name: Requested relative media path.
            content: File-like object being stored.
            max_length: Optional backend-specific max length.

        Returns:
            str: Final stored relative media path.
        """
        normalized_name = self.path_builder_class.build_tenant_media_name(name or content.name)
        return super().save(normalized_name, content, max_length=max_length)

    def generate_filename(self, filename: str) -> str:
        """ Normalize one generated media path with the active tenant folder.

        Args:
            filename: Relative media path generated by the field or caller.

        Returns:
            str: Tenant-aware generated media path.
        """
        normalized_filename = self.path_builder_class.build_tenant_media_name(filename)
        return super().generate_filename(normalized_filename)
